アカウント登録機能実装
maki-engineer/Original-SNS pull request #17
Opened 2022-11-13 14:34 UTC by o2yama

## 概要
ユーザー登録後、ユーザーのIDに紐づいたアカウントがなければ、アカウント登録させる機能を実装。
アイコンの登録とアカウントの複数登録機能は未実装。

## 詳細
* デザイン要修正

## 追加が必要な機能
* ユーザー1つにつき、複数のアカウントを作る機能
* アイコン（画像）登録の機能

2022-11-15 09:16 UTC, maki-engineer requested changes
ちょっといくつか気になるところがあるから確認オナシャス！

2022-11-15 09:16 UTC, maki-engineer commented on app/Http/Controllers/Account/AccountController.php
> +        $account = Account::where('user_id', $id);
$idって何の値が設定されてるん？

2022-11-15 09:30 UTC, maki-engineer commented on routes/web.php
> +    Route::post('/create_account', 'App\Http\Controllers\Account\AccountController@create')->name('account.create');
updateメソッドに対するルーティングが追加されてないと思う！
`Route::put('/update_account', 'App\Http\Controllers\Account\AccountController@update')->name('account.update');`
になりそうかな。

2022-11-15 09:30 UTC, maki-engineer commented on resources/views/components/register_account.blade.php
> +        @csrf
この@csrfっていうのは1つのformタグに対して1つ設定すればいいんじゃないかなって思ってるんだけど、どうして2つ設定してるん？
後、@method('POST')を4行目じゃなくて30行目に書いてるのは何故？

2022-11-19 00:25 UTC, o2yama commented on app/Http/Controllers/Account/AccountController.php
> +        $account = Account::where('user_id', $id);
$account_idに修正した！

2022-11-19 00:25 UTC, o2yama commented on resources/views/components/register_account.blade.php
> +        @csrf
これは完全にミス、、
ありがとう

2022-11-19 00:32 UTC, o2yama commented
@maki-engineer 
修正したから、確認お願いします

2022-11-19 01:28 UTC, maki-engineer requested changes

2022-11-19 01:28 UTC, maki-engineer commented on app/Http/Controllers/Account/AccountController.php
> +    public function update(CreateRequest $request, string $account_id)
ちょっと試してほしいんだけど、`dd($account_id)`で$account_idの中身見てもらえる？　多分値取ってこれてないんじゃないかな。（もしかしたら俺が知識不足なだけだと思うんだけど笑）

コードを見てみた感じたいせいはURLからユーザーのidを取得しようとしてるのかな？
となると、恐らくルーティングの方は`'/update_account/{userId}'`みたいになって、`string $account_id`じゃなくて`Request $accountId`になるんじゃないかなと思うんよね

そして、`$accountId = (int)$request->route('accountId')`でint化、んで`$account = Account::where('user_id', $accountId);`とすればいけるんじゃないかなと思ってるんよね

後ごめん、すごく細かいんだけど変数名はキャメルケースでオナシャス！m(_ _)m

2022-11-21 23:57 UTC, maki-engineer commented on app/Http/Controllers/Account/AccountController.php
> +    public function update(CreateRequest $request, string $account_id)
あ、なるほどね！　user_idを取ろうとしてたのか。　確かにそのやり方だったらルーティングもあれで大丈夫だね👍
cssファイルとかも上げてくれてサンキュー！
修正お疲れ様、LGTMです！

2022-11-21 23:58 UTC, maki-engineer approved these changes
細かいところも修正してくれてありがとね！
修正お疲れ様、LGTMです！

2022-11-22 00:00 UTC, merged