フォローする機能
maki-engineer/Original-SNS pull request #19
Opened 2022-11-27 13:24 UTC by maki-engineer

## 詳細

* フォローする機能を実装。

* 自分以外のプロフィール画面にはフォロー数、フォロワー数を表示しない機能を実装。

* プロフィール画面、フォロワー一覧画面、フォロワー一覧画面を実装。

* 一通り色々な画面の雛型を設計（デザインとか、あくまで仮）

* フォローするために必要なfollower_relationshipsテーブル作成。

## 把握してほしいこと

* 現状はAuth::id()と紐づけてしまっているため、今後アカウントを複数使うユーザーが現れると現状の処理ではバグが発生するため、一刻も早く修正する必要がある。

* プロフィール画面に自己紹介文を書いた方がいいと考えたため、accountsテーブルに自己紹介文を書くためのカラムを追加することを検討している。

* プロフィール画面に好きな項目(アニメとか)を追加することによって、趣味が合う人と繋がりやすくなるのではないかと思ったため、accountsテーブルに好きな項目を登録するためのカラムを追加、アカウント登録時に、好きな項目を入力（選択）する項目を追加することを検討している。

* 今後プロフィール画面からプロフィール情報を編集することが出来る機能を検討している。

2022-11-28 00:42 UTC, o2yama commented on routes/web.php
> +    Route::get('/user/{userId}', 'App\Http\Controllers\Account\AccountController@show')
nits
ここ、アカウントIDが入るはずだから、`'/user/{userId}'`より`/account/{accountId}`の方がいいかなと思った

2022-11-28 01:07 UTC, o2yama requested changes
コメントしたから、確認よろしく

2022-11-29 02:04 UTC, maki-engineer commented on database/migrations/2022_11_23_175746_add_user_id_to_tweets_table.php
> +            $table->foreign('user_id')->references('id')->on('accounts');
ルーティングをuserからaccountに変更する件とこの件に関してなんだけど、確かにその通りだなと感じたんだけど、変更するとなると色々なところも変更する必要があって、見落としがあった際にすごくめんどくさいことになりそうと思ったんよね。後開発メンバーも2人だけで、期限も迫ってきちゃってるから、このまま開発を進めていった方がいいんじゃないかなと思ってるんだけどどうかな？

そしてとりあえず中間発表とか最終発表を終わらせて余裕が出来たら修正するでどうだろうか。

2022-12-07 10:34 UTC, o2yama approved these changes
遅くなってごめん！
LGTM〜

2022-12-07 11:22 UTC, merged