サインアップ〜アカウント登録画面のUI実装
maki-engineer/Original-SNS pull request #22
Opened 2023-01-16 11:45 UTC by o2yama

## 概要
会員登録〜アカウント登録画面のUIを実装

「最初からやり直す」ボタンは、アカウント登録でしか使わなそうだから、register_account.blade.phpの方に置くようにしましたー（`index.blade.php`で出てる差分は、「最初からやり直す」ボタン削除しただけね）

2023-01-18 10:29 UTC, maki-engineer requested changes
恐らく致命的なバグが1点と、聞きたいことが1点あったから、確認オナシャス！

2023-01-18 10:29 UTC, maki-engineer commented on resources/views/components/check-box.blade.php
> +@props(['disabled' => false])
[q] : このcheck-box.blade.php ファイルってどんなことをしてるん？

2023-01-18 10:29 UTC, maki-engineer commented on resources/views/components/register_account.blade.php
> +            <form action="{{ route('logout') }}" method="post">
[must] : 最初からやり直すボタンについて、アカウント登録画面に飛んで、最初からやり直すのボタンを押したらこんな画面に飛んじゃったんだけど、ちょっとたいせいも試してみてもらえる？多分49行目らへんが原因なのかな？

![SpaChat - Google Chrome 2023_01_18 19_17_36](https://user-images.githubusercontent.com/71965690/213147962-1ecafab7-e3a5-43f8-96ba-3725e1c955ad.png)

2023-01-20 23:45 UTC, o2yama commented on resources/views/components/check-box.blade.php
> +@props(['disabled' => false])
これはアカウント登録画面で「年齢をあいまいに表示する」と「年齢を表示しない」で使ってるチェックボックス！
他にもチェックボックス使う場面あるかなと思って、共通コンポネントとして作っておいた。

2023-01-20 23:49 UTC, o2yama commented on resources/views/components/register_account.blade.php
> +            <form action="{{ route('logout') }}" method="post">
```
<form method="POST" action="{{ route('account.create') }}">

</form>
```
「最初からやり直す」ボタンを、このフォームの中に入れちゃってたのが原因でした、
外側に出して整形したから確認お願いしますー

2023-01-21 01:58 UTC, maki-engineer commented on resources/views/components/check-box.blade.php
> +@props(['disabled' => false])
なるほど！　確かにそうした方が便利だわ！
コンポネント化サンキュー！👍

2023-01-21 02:06 UTC, maki-engineer commented on resources/views/components/register_account.blade.php
> +            <form action="{{ route('logout') }}" method="post">
確認してみたところ、確かにエラーは直されてタイトル画面に戻ったんだけど、再度同じメールアドレスで新規登録しようとすると「そのメールアドレスは既に使われています」ってなって登録できなくなっちゃってるな......

メールアドレスやパスワードを保存するタイミングをアカウント登録した時にしないといけない感じかな。

2023-01-21 03:08 UTC, o2yama commented on resources/views/components/register_account.blade.php
> +            <form action="{{ route('logout') }}" method="post">
> 「そのメールアドレスは既に使われています」ってなって登録できなくなっちゃってる
Userテーブルに残っちゃってるからだね

りょうかい
メール認証する方法で実装し直すね

2023-01-28 02:08 UTC, o2yama commented on resources/views/components/register_account.blade.php
> +            <form action="{{ route('logout') }}" method="post">
@maki-engineer 
メール認証実装すると差分が多くなってわかりづらいから、Viewについての指摘がなければ、このサインアップ画面のViewの実装を先にマージしたいんだけど、良い？

2023-01-28 13:38 UTC, maki-engineer commented on resources/views/components/register_account.blade.php
> +            <form action="{{ route('logout') }}" method="post">
@o2yama 
全然それでOKよ！というかむしろメール認証の実装までやってくれるとは思ってなかったから無理だけはしないようにね！

2023-01-28 13:39 UTC, maki-engineer approved these changes
メールの認証については別のタスクとして行うということで、LGTMで！
お疲れ様！
![LGTM](https://image.lgtmoon.dev/195363)

2023-01-31 07:47 UTC, merged